{
 "title": "Request Overview",
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status_code=~\"^[1-3][0-9][0-9]$\"}[$__rate_interval]))",
     "legendFormat": "good (HTTP < 400)"
    },
    {
     "expr": "sum(rate(http_requests_total{status_code=~\"^[4-5][0-9][0-9]$\"}[$__rate_interval]))",
     "legendFormat": "bad (HTTP >= 400)"
    }
   ]
  },
  {
   "title": "Bad Requests by Route (HTTP >= 400)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status_code=~\"^[4-5][0-9][0-9]$\"}[$__rate_interval])) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Good Requests by Route (HTTP < 400)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status_code=~\"^[1-3][0-9][0-9]$\"}[$__rate_interval])) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 16, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Unique Users",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 16, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "unique_users{period=\"1h\"}",
     "legendFormat": "1h unique users"
    }
   ]
  },
  {
   "title": "Top Bad Requests by Route (HTTP >= 400)",
   "type": "table",
   "gridPos": { "x": 0, "y": 24, "w": 12, "h": 10 },
   "targets": [
    {
     "expr": "topk(10, max_over_time((sum(rate(http_requests_total{status_code=~\"^[4-5][0-9][0-9]$\"}[5m])) by (method, route, status_code))[$__range:]))"
    }
   ]
  },
  {
   "title": "Top Good Requests by Route (HTTP < 400)",
   "type": "table",
   "gridPos": { "x": 12, "y": 24, "w": 12, "h": 10 },
   "targets": [
    {
     "expr": "topk(10, max_over_time((sum(rate(http_requests_total{status_code=~\"^[1-3][0-9][0-9]$\"}[5m])) by (method, route, status_code))[$__range:]))"
    }
   ]
  },
  {
   "title": "Top Routes by Latency",
   "type": "table",
   "gridPos": { "x": 0, "y": 34, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "topk(10, max_over_time((histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[$__rate_interval])) by (le, route)))[$__range:]))"
    }
   ]
  }
 ]
}